

const LocalizedString = {
  af_za: {
    'EN_ZA Grade 1': 'AF_ZA Graad 1',
    'EN_ZA Worksheets': 'AF_ZA-Wekstate',
    'Grade': 'Graad',
    'Assigned': 'Toegewys',
    'Recent Feedback': 'Nuutste terugvoer',
    'Students': 'Studente',
    'Worksheets': 'Werkstate',
    'Leaderboard': 'Leierbord',
    'Progress': 'Vordering',
    'Video Library': 'Video Biblioteek',
    '0 to 20 complete': '0 van 20 voltooi',
    'Begin': 'Begin',
    'Resume': 'Hervat',
    'Solve the word problem': 'Los die woordprobleem op',
    'Gina has 28 apples. If she wants to give her friends 1/4 of the apples, how many does each of the friends get?': 'Gina het 28 appels. As sy vir haar vreinde 1/4 van die appels will gee, hoeveel sal elke vriend kry?',
    "Count in 25's between 9150 and 9325": "Tel in 25's tussen 9150 en 9325",
    'EN_ZA Grade2': 'AF_ZA Graad 2',
    'Total Questions': 'Totale Vrae',
    'Questions': 'Vrae',
    'Correct Questions': 'Korrecte Vrae',
    'Incorrect Questions': 'Verkeerde Vrae',
    'Questions Skipped': 'Vrae Oorgeslaan',
    'Total Time': 'Totale Tyd',
    'Select a child to begin the skills assessment.': 'Kies N Kind om met die vaardigheidsassessering te being',
    'Or select parent setting to add new plans and students to this account.': 'Of kies Ouer-stellings on nuwe planne en leerders by hierdie rekening te voeg',
    'Parent Settings': 'Ouer-stellings',
    'Manage Your Account': 'Bestuur jou rekening',
    'Congratulations on completing the Diagnostic test': 'Geluk met jou voltooiing van die diagnostiese toets!',
    "Click here for a detailed report on your child's performance.": 'Klik hier vir n gedetailleerde verslag oor jou kind se vordering',
    'Get to know Tabtor': 'Leer Via Afrika Tabtor ken',
    'Personalised maths on tablets': 'Verpersoonlikte wiskunde op tablette',
    'User Name / Email': 'Gebruikernaam / E-posadres',
    'Password': 'Wagwoord',
    'Log In': 'Meld aan',
    'Reset Password': 'Stel nuwe wagwoord in',
    'Reset Your Password':'Herstel jou wagwoord',
    'Log In with': 'Meld aan met',
    'Not enrolledyet? Sign up today': 'Nog nie ingeskryf nie? Sluit vandag aan',
    'You are about to start a test. We recommend uninterrupted time and a quiet space. Your coach will tailor your assignments based on the test results.': "Jy gaan nou met 'n toets begin. Ons beveel ononderbroke tyd en 'n stil omgewing aan. Jou tutor sal jou take op grond van die toets pasmaak.",
    'There will be no video tutorials.': 'Daar sal geen videotutoriale wees nie.',
    'No second attempts during a test.': 'daar is geen tweede probeerslag tydens toetse nie.',
    'You can revise your answers before the final submission.': 'Jy kan jou antwoorde hersien voordat jy dit finaal indien.',
    'Good luck!': 'Sterkte!',
    'All Time': 'Onoorwonne',
    'This month': 'Hierdie maand',
    'Global': 'Alle lande',
    'My country': 'My land',
    'All grades': 'Alle grade',
    'My grade': 'My graad',
    'Leaders': 'Voorlopers',
    'Lifetime': 'points Lewenslange punte',
    'Country': 'Land',
    ' Grade': 'Graad',
    'Medals': 'Medalje',
    'Points this month': 'Punte vir die maand',
    'Select': 'asseblief',
    'Cancel': 'Kanselleer',
    'Submit as is': 'Handig in',
    'Continue': 'Gaan voort',
    'Submit': 'Dien in',
    'Gold': 'Goud',
    'Log Out': 'Teken uit',
    'Reward Points': 'beloon punte',
    'Correct Answers': 'Korrekte Antwoorde',
    'Incorrect Answers': 'Verkeerde Antwoorde',
    'Second Tries': 'Tweede Pogings',
    'Skipped Answers': 'Oorgeslane Antwoorde',
    'Pending Questions': 'hangende Vrae',
    'Suggested': 'oorgestelde',
    'Suggested Time': 'Voorgestelde tyd',
    'Pts Earned': 'Punte verdien',
    'Points Earned': 'Punte verdien',
    'Choose Plan': 'Kies plan',
    'Start': 'Begin',
    'Progress Report': 'Vorderingsverslag',
    'Welcome': 'Welkom',
    'back': 'terug',
    'You will first warm up with 5 sample questions and then you will attempt 15 questions that will comprise your diagnostic assessment. The diagnostic assessment is used to build a personalized learning plan just for you.': "Jy gaan eers opwarm met vyf voorbeeldvrae en dan gaan jy 15 vrae beantwoord as deel van jou diagnostiese assessering. Die diagnostiese assessering word gebruik om 'n persoonlike leerplan net vir jou saam te stel.",
    'Select a Child to Begin the Diagnostic Test': "Kies 'n Kind om te begin die Diagnostiese Toets",
    'Points Summary': 'punte Opsomming',
    'Summary': 'Opsomming',
    'Score Summary': 'telling Opsomming',
    'Awaiting Feedback': 'wag Terugvoer',
    'Your worksheet has been submitted to your coach for review. Check back later.': 'Jou werkblad is om jou afrigter vir hersiening voorgelê. Loer later weer in.',
    'Show All': 'wys Alles',
    'Incorrect / Flagged': 'Foutief / gevlag',
    'Complete': 'Voltooi',
    'Remember to look at where you made errors. Review my notes.': 'Onthou om te kyk waar jy foute gemaak het. Hersien my notas.',
    'Final Score': 'Finale Punt',
    'Penalty: 2nd Try': 'Straf: 2de Poging',
    'Learnosity question render goes here': 'Learnosity-vraag vertoning kom hier',
    'Scribbles from Coach': 'Afrigter se krabbels',
    "Coach's Scribbles": 'Afrigter se krabbels',
    'Second Attempt used': 'Tweede Poging gebruik',
    'Flag raised': 'Vlaggie gehys',
    'Audible notes': 'Hoorbare notas',
    'Your Answer': 'Jou Antwoord',
    'Awesome! You did great!': 'Fantasties! Jy het wonderlik gedoen!',
    'Total Points Earned': 'Totale punte verdien',
    'Skipped Questions': 'oorgeslaan Vrae',
    'Accuracy': 'akkuraatheid',
    'Triple Point Bonus': 'Triple Point Bonus',
    'Speed Bonus': 'spoed Bonus',
    'Guided by Expert Coaches. Powered by AI.': 'Begelei deur Kundige Afrigters. KI-gedrewe.',
    'Your worksheet has been submitted to your coach for review.': 'Jou werkvel is vir hersiening by jou afrigter ingedien',
    'Go over the features of our app to help your child get acclimated.': 'Gaan deur die kenmerke van ons app om jou kind te help aanpas.',
    'Learn about your child’s needs and help you select the right program.': 'Leer jou kind se behoeftes ken en help jou om die regte program te kies.',
    'Share best practices to achieve success with the program.': 'Deel beste praktyke om sukses met die program te behaal.',
    "The call will help us better understand your child's needs and goals so that we can pair your child with the right Tabtor tutor. Our goal is to make sure you get a complete experience of Via Afrika Tabtor Maths.": "Die oproep help ons om jou kind se behoeftes en doelwitte beter te verstaan sodat ons jou kind kan plaas by die regte Thinkster-afrigter. Ons doel is om seker te maak dat jy 'n volledige ervaring van Thinkster Math kry.",
    'Use the form below to reset your password.': 'Gebruik die vorm hieronder om jou wagwoord te herstel.',
    'Reset My Password': 'Herstel My Wagwoord',
    'Not Tested': 'Nie Getoets Nie',
    'Manage Plans': 'Bestuur Planne',
    'Manage Your Plans': 'Bestuur jou Planne',
    'Your Plans': 'jou Planne',
    'Account Settings': 'Rekeningstellings',
    'Payment': 'Betaling',
    'Used the number word charts to find the number and number name.': 'Het die getalwoordgrafieke gebruik om die getal en getalnaam te kry',
    'Number Words': 'Getalwoorde',
    'No Video tutorials for this Assignment': 'Geen video-turoriale vir hierdie opdrag nie',
    'Switch to 3 Month Billing': 'Skakel om na 3-maandelikse rekening-ontvangs.',
    'Starting your next billing cycle, all your plans will be charged on a 3 month billing cyle.': "Begin jou volgende rekening-ontvangsiklus; al jou planne sal verander na 'n 3-maandelikse rekening-ontvangsiklus.",
    'Based on your current plan': 'Gebaseer op jou huidige plan',
    "you'll save $20 a month!": 'sal jy $20 per maand spaar!',
    'Your upcoming payment of': 'Jou komende betaling van',
    'will be processed on': 'sal verwerk word op',
    'Your Visa ending in': 'Jou Visa wat eindig op',
    'Your': 'Jou',
    'ending in': 'wat eindig op',
    'will be charged automatically.': 'sal outomaties verander word.',
    'Switch to 3 Month Billing &amp; Save!': 'Skakel om na 3-maandelikse rekening-ontvangs ... en spaar!',
    "No thanks, I don't like saving money.": 'Nee dankie. Ek hou nie daarvan om geld te spaar nie.',
    'Gold Plan': 'Goue Plan',
    'Active': 'Aktief',
    'Update Plan': 'Pas Plan aan',
    'Up to 2 Phone Calls Per Month': 'Tot 2 Telefoonoproepe Per Maand',
    '10-15 minutes each': '10-15 minute elk',
    'Homework Help': 'Huiswerkhulp',
    'Test Prep': 'Toetsvoorbereiding',
    'Choose Silver Plan': 'Kies Silwer Plan',
    '2 Sessions': '2 Sessies',
    'One-on-one': 'Individuele',
    'online coaching': 'aanlyn afrigting',
    "Click here for detailed report on your child's performance": "Kliek hier vir 'n gedetailleerde verslag oor jou kind se werksprestasie",
    'Cancel This Plan': 'Kanselleer Hierdie Plan',
    'You have not attempted some questions.': 'Jy het party vrae nie probeer doen nie',
    'Clear all scribbles?': 'Verwyder al jou krabbels?',
    'Submitting the worksheet.': 'Hoe om die werkvel in te dien.',
    'Add New Plan': 'Nuwe Plan',
    'Subscription Details': 'inskrywing Besonderhede',

    // pending translations
    'Your Skills Assessment is being submitted.': 'AF Trasnlation not available',
    'Your Worksheet is being submitted': 'AF Trasnlation not available',

    'Awesome! You did great!	Fantasties!': 'Jy het wonderlik gedoen!',
    'This is a quiz.  We are testing to see if you have learned what was taught previously on practice work.  Your coach will adjust your work based on the test results.': 'Hierdie vrae sal ons help toets om te sien of jy uit vorige oefenwerk geleer het. Jou studie-leier sal jou werk aanpas op grond van die toetsuitslae.',
    'There are no video tutorials': 'Daar is geen video-tutoriale nie.',
    'You will get two chances to answer the questions': 'Jy sal twee kanse kry om die vrae te beantwoord.',
    'This is a practice worksheet.': "Hierdie is 'n oefenwerkstaat.",
    'Show your work so the coach can see which strategy you used to solve the problems': 'Wys jou werk sodat die studie-leier kan sien watter strategie jy gebruik het om die probleme op te los.',
    "There is a video tutorial to help you understand how to solve the problems": "Daar is 'n video-tutoriaal om jou te help verstaan hoe om die probleme op te los.",
    'Try to work on your own.  Let your coach know if your parent helped in solving the problems': 'Probeer op jou eie werk. Laat jou studie-leier weet as jou ouer jou probleme help oplos het.',
    'Do your best!': 'Doen jou bes!',
    'You will now start the test. Please read each question carefully and answer to the best of your ability.': 'Jy sal nou die toets begin. Lees asseblief elke vraag sorgvuldig en en beantwoord dit so goed as wat jy kan.',

    'Please attempt the question!': 'Probeer asseblief die vraag!',

    'Referral Code': 'Verwysingskode',
    'Promo Code': 'Promosiekode',
    'Accelerate': 'Versnel',
    'Total Savings': 'Totale besparings',
    'Subscription Total': 'Inskrywingstotaal',
    'Free Trial': 'Gratis proeflopie',
    'Monthly Plan': 'Maandelikse plan',
    'Subtotal': 'Subtotaal',
    'Free': 'Gratis',
    'Monthly Billing Summary': 'Opsomming van maandelikse betaalsiklus',
    'Modify Plan': 'Pas plan aan',
    'month': 'Maandelikse plan',

    'Welcome to the Thinkster Product Tour': 'Welkom by die Thinkster-produktoer',
    'Choose a grade below to view sample questions.': "Kies 'n graad hieronder om voorbeeldvrae te sien.",
    'Kindergarten': 'Graad R',
    'Coach Feedback': 'studie-leier Terugvoe',
    'Curriculum': 'Kurrikulum',
    'Rewards': 'Belonings',
    'Submitted': 'Ingedien',
    'Inactive': 'Onaktiewe',
    'Lifetime Reward Points': 'Lewenslange beloningspunte',
     
  },
  en_gb: {
    'Grade': 'Year',
  }
};

export default LocalizedString;

