module.exports = {
  isProd: true,
  apiEndPoint: 'https://data.tabtor.com',
  legacyAPIEndPoint: 'https://tapi.tabtor.com',
  tutoringSessionsAPIEndPoint: 'https://tutoring-sessions.hellothinkster.net',
  leaderboardAPIEndPoint: 'https://node.tabtor.com',
  leaderboardName: 'tabtor',
  leaderboardAvatarBucket: 'tabtor-profile-avatars',
  profilePictureBucket: 'tabtor-profile-pictures',
  enrollURL: 'https://enroll.hellothinkster.com',
  enrollURLToPricing: 'https://enroll.hellothinkster.com/pricing-math-programs',
  passwordResetURL: 'https://parents.hellothinkster.com/PasswordChange.php',
  viaAfrikaEnrollURL: 'http://viaafrika.tabtor.com/viaafrika.php',
  showWhiteboard: true,
  showMangeParentSettings: true,
  showVideoLibrary: true,
  intercom_app_id: 'ab72j9ke',
  baseServiceId: 'Starter',
  showReferAFriend: true,
  // Referral SaasQuatch
  REFERRALSAASQUATCH_API_KEY: 'LIVE_9ecs6x28GoEtDcYuE2ZTc2Od5kgF5Y5G',
  REFERRALSAASQUATCH_TENANT_ALIAS: 'ajhzj2kx99d1d',
  purchaseProductURL: 'https://enroll.hellothinkster.com/math-worksheets-store',
  purchaseSessionURL: 'https://enroll.hellothinkster.com/tutoring-sessions',
  productTourURL: 'https://demo.hellothinkster.com/product-tour',
  ycmbSessionsURL: 'https://thinkstertutoring.youcanbook.me/',
};
