module.exports = {
  isProd: false,
  apiEndPoint: 'https://data-sandbox.tabtor.com',
  legacyAPIEndPoint: 'https://sandbox.tabtor.com/portal/',
  tutoringSessionsAPIEndPoint: 'http://tutoring-sessions-sandbox.hellothinkster.net',
  leaderboardAPIEndPoint: 'https://node.tabtor.com',
  leaderboardName: 'sandbox',
  leaderboardAvatarBucket: 'sandbox-profile-avatars',
  profilePictureBucket: 'sandbox-profile-pictures',
  enrollURL: 'https://enroll-sandbox.hellothinkster.com',
  enrollURLToPricing: 'https://enroll-sandbox.hellothinkster.com/pricing-math-programs',
  passwordResetURL: 'https://parents.hellothinkster.com/PasswordChange.php',
  viaAfrikaEnrollURL: 'http://viaafrika-sandbox.tabtor.com/viaafrika.php',
  showWhiteboard: true,
  showMangeParentSettings: true,
  showVideoLibrary: true,
  intercom_app_id: 'ab72j9ke',
  baseServiceId: 'Starter',
  showReferAFriend: true,
  // Referral SaasQuatch

  REFERRALSAASQUATCH_API_KEY: 'TEST_SVWtxdQ8levUbGFU0AyzdHZUqbRwHXEz',
  REFERRALSAASQUATCH_TENANT_ALIAS: 'test_a5pf1cc9tijke',
  purchaseProductURL: 'https://enroll-sandbox.hellothinkster.com/math-worksheets-store',
  purchaseSessionURL: 'https://enroll-sandbox.hellothinkster.com/tutoring-sessions',
  productTourURL: 'https://demo-sandbox.hellothinkster.com/product-tour',
  ycmbSessionsURL: 'https://thinkstertutoring-sandbox.youcanbook.me/',
};
