const videoMeta = {
  K: {
    'Number Representation': [
      'Counting with Illustrations',
      'Number Line',
      'Number Names',
      'Pictorial Models',
      'Count by Ones & Tens',
    ],
    'Number Relation': [
      'Skip Counting',
      'Comparison of Numbers',
      'Successive Numbers',
    ],
    Addition: [
      'Addition with Illustrations',
      'Simple Addition',
      'Number Bonds',
      'Decomposing Numbers',
      'Number Line',
      'Properties of Addition',
      'Addition Word Problems',
    ],
    Subtraction: [
      'Subtraction with Illustrations',
      'Simple Subtraction',
      'Number Line',
      'Subtraction Word Problems',
    ],
    'Measurement & Data': [
      'Comparison of Objects',
      'Categorization of Objects',
    ],
    Geometry: [
      'Working with Shapes',
      'Properties of Polygons',
      'Correlate 2-D & 3-D Shapes',
      'Object Position',
    ],
  },
  1: {
    'Number Representation': [
      'Number Names',
      'Ones, Tens & Hundreds',
      'Subtraction using Place Value',
      'Ordinal Numbers',
    ],
    'Number Relation': [
      'Skip Counting',
      'Comparing Numbers',
      'Addition & Subtraction',
      'Mathematical Symbols in Equations',
      'Logical Reasoning',
      'Relative Position',
    ],
    Addition: [
      'Simple Addition',
      'Properties of Addition',
      'Number Bonds',
      'Fact Families',
      'Comparing Expressions',
      'Balancing Equations',
      'Addition Word Problems',
    ],
    Subtraction: [
      'Simple Subtraction',
      'Fact Families',
      'Equivalent Expression',
      'Balancing Equations',
      'Subtraction Word Problems',
      'Addition & Subtraction Equations',
    ],
    'Measurement & Data': [
      'Telling Time',
      'Calculation of Time',
      'Calendar Activities',
      'Counting Money',
      'Length Measurements',
      'Understanding Patterns',
      'Data Interpretation',
    ],
    Geometry: [
      'Defining vs Non-defining Attributes',
      'Correlate 2-D & 3-D Shapes',
      'Partitions',
      'Turns, Rotation & Direction',
    ],
  },
  2: {
    'Number Representation': [
      'Number Names',
      'Ones, Tends & Hundreds',
      'Addition using Place Value',
      'Subtraction using Place Value',
      'Odd & Even Numbers',
    ],
    'Number Relation': [
      'Comparing Numbers',
      'Number Line',
      'Skip Counting',
      'Addition & Subtraction in Words',
      'Function Rules',
    ],
    Addition: [
      'Adding by Ones & Tens',
      'Repeated Addition',
      'Simple Addition',
      'Addition with Regrouping',
      'Balancing Equations',
      'Addition Word Problems',
    ],
    Subtraction: [
      'Simple Subtraction',
      'Subtraction without Regrouping',
      'Subtraction with Regrouping',
      'Balancing Equations',
      'Subtraction Word Problems',
      'Equivalent Equation',
      'Comparing Expressions',
    ],
    'Measurement & Data': [
      'Telling Time',
      'Comparing Time',
      'Time Word Problems',
      'Counting Money',
      'Conversion of Money',
      'Operations on Money',
      'Length, Weight & Capacity',
      'Comparing Lengths',
      'Data Interpretation',
    ],
    Geometry: [
      'Identifying Shapes',
      'Defining vs Non-defining Attributes',
      'Partitions',
      'Symmetry',
      'Turns, Rotation & Direction',
    ],
  },
  3: {
    'Number Representation': [
      'Number Names',
      'Understanding Place Value',
      'Number Sense',
      'Rounding Numbers',
      'Estimation',
      'Odd & Even Numbers',
      'Roman Numerals',
    ],
    'Number Relation': [
      'Comparison of Numbers',
      'Skip Counting',
      'Mathematical Symbols in Equations',
      'Relative Position',
    ],
    Addition: [
      'Simple Addition',
      'Addition with Regrouping',
      'Balancing Equations',
      'Addition Word Problems',
      'Multi-step Word Problems',
    ],
    Subtraction: [
      'Subtraction with Regrouping',
      'Balancing Equations',
      'Subtraction Word Problems',
      'Order of Operations',
      'Multi-step Word Problems',
    ],
    Multiplication: [
      'Repeated Addition',
      'Simple Multiplication',
      'Balancing Equations',
      'Multiplication Word Problems',
      'Multiplication Sequences',
      'Equivalent Expression',
      'Comparing Expressions',
      'Estimation',
      'Applying Multiplication',
    ],
    Division: [
      'Simple Division',
      'Balancing Equations',
      'Division Word Problems',
      'Equivalent Expression',
      'Comparing Expressions',
      'Estimation',
      'Multi-step Word Problems',
    ],
    Fractions: [
      'Understanding Fractions',
      'Number Line for Fraction',
      'Equivalent Fractions',
      'Comparing Fractions',
      'Fraction Word Problems',
      'Types of Fractions',
    ],
    'Measurement & Data': [
      'Telling Time',
      'Conversion of Time',
      'Time Calculation',
      'Calendar Activities',
      'Time Word Problems',
      'Counting Money',
      'Conversion of Money',
      'Operations on Money',
      'Measuring Length, Weight & Temperature',
      'Comparison of Lengths, Weights & Capacities',
      'Area & Perimeter',
      'Data Interpretation',
    ],
    Geometry: [
      'Building Blocks',
      'Defining vs Non-defining Attributes',
      'Partitions',
    ],
    Probability: [
      'Probability Outcomes',
    ],
  },
  4: {
    'Number Representation': [
      'Number Names',
      'Understanding Place Value',
      'Rounding Numbers',
      'Estimation',
      'Roman Numerals',
    ],
    'Number Relation': [
      'Addition & Subtraction in Words',
      'Comparison of Numbers',
      'Number Sequence',
      'Odd and Even Numbers',
      'Logical Reasoning',
    ],
    Addition: [
      'Simple Addition',
      'Addition with Regrouping',
      'Balancing Equations',
      'Multi-step Word Problems',
    ],
    Subtraction: [
      'Simple Subtraction',
      'Balancing Equations',
      'Multi-step Word Problems',
    ],
    Multiplication: [
      'Simple Multiplication',
      'Properties of Multiplication',
      'Order of Operations',
      'Multi-step Word Problems',
    ],
    Division: [
      'Simple Division',
      'Balancing Equations',
      'Long Division',
      'Rules of Divisibility',
      'Division Word Problems',
      'Comparison of Expressions',
      'Order of Operations',
      'Division with Remainder',
      'Multi-step Word Problems',
      'Decimal Division',
      'Prime & Composite Numbers',
    ],
    'Factors & Multiples': [
      'Common Factors & HCF',
      'Common Multiples & LCM',
      'Factors & Multiples Word Problems',
    ],
    Fractions: [
      'Decomposing Fractions',
      'Equivalent Fractions',
      'Simplest Form',
      'Fraction Conversion',
      'Comparison of Fractions',
      'Fraction Addition',
      'Fraction Subtraction',
      'Fraction Word Problems',
      'Mixed Fractions',
      'Fraction Multiplication',
    ],
    Decimal: [
      'Number Line for Decimals',
      'Decimal Conversion',
      'Comparison of Decimals',
      'Rounding Decimals',
      'Decimal Addition',
      'Decimal Subtraction',
      'Number Sequence',
      'Order of Operations',
    ],
    'Measurement & Data': [
      'Telling Time',
      'Conversion of Time',
      'Calculation of Time',
      'Time Word Problems',
      'Age Word Problems',
      'Counting Money',
      'Conversion of Money',
      'Operations on Money',
      'Unitary Methods Word Problems',
      'Conversion of Metric Units',
      'Conversion of Standard Units',
      'Lengths, Weights & Capacities Word Problems',
      'Area & Perimeter',
      'Angles',
      'Data Interpretation',
    ],
    Geometry: [
      'Lines & Angles',
      '2-D Figures',
      'Lines of Symmetry',
      'Understanding Circles',
    ],
    Probability: [
      'Probability Outcomes',
    ],
  },
  5: {
    'Number Representation': [
      'Number Sense',
      'Understanding Place Value',
      'Estimation',
      'Roman Numerals',
    ],
    'Number Relation': [
      'Comparison of Numbers',
      'Numerical Expressions',
      'Number Sequences',
      'Understanding Patterns',
      'Order of Operations',
      'Logical Reasoning',
    ],
    'Addition & Subtraction': [
      'Problem Solving',
    ],
    Multiplication: [
      'Simple Multiplication',
      'Multiplication Word Problems',
    ],
    Division: [
      'Long Division',
      'Balancing Equations',
      'Rules of Divisibility',
      'Division Word Problems',
    ],
    'Factors & Multiples': [
      'Common Factors & GCF',
      'Common Multiples & LCM',
    ],
    Fractions: [
      'Reduction of Fractions',
      'Fraction Conversion',
      'Least Common Denominator',
      'Fraction Addition',
      'Fraction Subtraction',
      'Fraction Multiplication',
      'Fraction Division',
      'Operations on Fractions',
      'Fraction Word Problems',
      'Percentage Conversion',
      'Mixed Number Word Problems',
      'Area Model',
      'Order Of Operations',
    ],
    Decimal: [
      'Number Names',
      'Expanded Form for Decimals',
      'Building & Placement of Decimals',
      'Decimal Addition & Subtraction',
      'Decimal Multiplication',
      'Decimal Division',
      'Order of Operations',
    ],
    'Measurement & Data': [
      'Metric Units',
      'Standard Units',
      'Measurement Word Problems',
      'Area & Perimeter',
      'Elapsed Time',
      'Percentages',
      'Temperature Conversion',
      'Volume of Prisms',
      'Data Interpretation',
    ],
    Geometry: [
      'Types of Angles',
      'Types of Triangles',
      'Area of Polygons',
      'Coordinate Pairs',
      'Circles',
    ],
    Probability: [
      'Understanding Probability',
      'Mean, Median, Mode, Range of Data',
    ],
  },
  6: {
    'Number Representation': [
      'Numerical Expressions',
      'Face Value and Place Value',
      'Prime & Composite Numbers',
      'Estimation',
      'Exponential Notation',
      'Scientific Notation',
      'Absolute Value',
      'Coordinate Plane',
      'Ordered Pairs',
    ],
    'Number Relation': [
      'Number Line',
      'Negative Numbers',
      'Comparison of Numbers',
      'Properties of Multiplication',
      'Number Sense',
      'Exponents',
      'Exponent Sequence',
      'Order of Operations',
    ],
    Addition: [
      'Addition of Integers',
      'Number Sequence',
      'Addition of Absolute Values',
    ],
    Subtraction: [
      'Integer & Decimal Subtraction',
    ],
    Multiplication: [
      'Properties of Multiplication',
    ],
    Division: [
      'Long Division',
    ],
    Decimal: [
      'Decimal Addition',
      'Decimal Subtraction',
      'Decimal Multiplication',
      'Decimal Division',
    ],
    'Factors & Multiples': [
      'HCF & LCM',
    ],
    Fractions: [
      'Fraction Conversion',
      'Fraction Addition',
      'Fraction Subtraction',
      'Fraction Multiplication',
      'Fraction Division',
      'Number Sequence',
    ],
    'Ratio & Proportion': [
      'Introduction to Ratios',
      'Equivalent Ratio',
      'Proportional Ratio',
      'Unit Rates',
      'Comparison of Ratios',
      'Coordinate Pairs',
    ],
    'Measurement & Data': [
      'Percentages',
      'Circle Graphs',
      'Measurement & Data Word Problems',
      'Simple Interest',
      'Speed, Distance & Time',
    ],
    Geometry: [
      'Area of Polygons',
      'Angles in a Polygon',
      '3D Shapes & Nets',
      'Measuring Volume',
      'Triangles',
      'Circles',
    ],
    Algebra: [
      'Algebraic Expressions',
      'Dependent & Independent Variables',
      'Algebraic Inequalities',
      'Variables in Equations',
      'Algebraic Addition',
      'Algebraic Subtraction',
      'Algebraic Multiplication',
      'Algebraic Division',
    ],
    Probability: [
      'Statistical Questions & Samples',
      'Mean, Median, Mode, Range',
      'Interpretating Data',
    ],
  },
  7: {
    'Number System': [
      'Understanding Rational Numbers',
      'Absolute Value of Rational Numbers',
      'Additive Inverse',
      'Properties of Addition & Subtraction of Rational Numbers',
      'Properties of Multiplication & Division of Rational Numbers',
      'Multiplication of Rational Numbers',
      'Division of Rational Numbers',
      'Operations on Rational Numbers',
      'Rational & Irrational Numbers',
    ],
    Algebra: [
      'Linear Expressions',
      'Algebraic Expressions',
      'Properties of Operations for Algebraic Expressions',
      'Algebraic Equations',
      'Algebraic Inequalities',
    ],
    'Ratio & Proportion': [
      'Comparing Ratios',
      'Proportional Relationship',
      'Constant of Proportionality',
      'Proportional Relationship using Equations',
      'Proportional Relationship using Graphs',
      'Word Problems on Ratio & Percent',
      'Inverse Variation',
      'Transitive Relationship',
    ],
    Geometry: [
      'Types of Angles',
      'Area & Perimeter of Circles',
      '2D Cross Section of 3D Images',
      'Composite Shapes',
      'Scale Factor',
    ],
    Probability: [
      'Representative Data',
      'Sample Size & Data',
      'Measures of Center & Variability',
      'Comparison of Data',
      'Probability of Events',
      'Theoretical & Experimental Probability',
      'Probability Models',
      'Compound Events',
      'Tree Diagrams',
    ],
  },
  8: {
    'Number System': [
      'Introduction to Irrational Numbers',
      'Square Roots',
    ],
    Algebra: [
      'Properties of Exponents',
      'Powers & Roots',
      'Scientific Notation',
      'Operations on Numbers',
      'Slope of a Line',
      'y-Intercept in Graphs & Similar Triangles',
      'Solutions of Equations',
      'Linear Equations',
      'System of Linear Equations',
      'Graphs & Number of Solutions',
      'Simple Algebraic Problems',
    ],
    Functions: [
      'Function Rule, Domain & Range',
      'Functions & Formats',
      'Linear Functions',
      'Linear Models',
      'Characteristics of Graphs',
    ],
    Geometry: [
      'Rotation, Reflection & Translation of Lines',
      'Transformation of Angles',
      'Transformation of Parallel Lines',
      'Congruent Images',
      'Dilation of 2D Figures',
      'Similar Images',
      'Transversal Lines and Angles',
      'Pythagorean Theorem',
      'Applications of Pythagorean Theorem',
      'Distance between Points on a Coordinate Grid',
      'Volumes of Cones, Cylinders and Spheres',
    ],
    Probability: [
      'Scatter Plots',
      'Data & Line of Best Fit',
      'Linear Models',
      'Two-way Tables & Association between Variables',
    ],
  },
  meta: [
    {
      title: 'Counting numbers and objects, understanding addition and subtraction, and introducing them to spatial thinking, 2-D & 3-D shapes.',
      videos: 229,
      concepts: 6,
    },
    {
      title: 'Solving addition & subtraction word problems using different strategies, telling time, counting money and connect shapes & their attributes.',
      videos: 232,
      concepts: 6,
    },
    {
      title: 'Multistep word problems, multiplication, measuring & estimating lengths in standard units, drawing 2-D & 3-D shapes, time & money.',
      videos: 264,
      concepts: 6,
    },
    {
      title: 'Mastering multiplication & division, multi-step word problems using different operations, fractions, solving for area & perimeter, and identify 2-D shapes by sides and angles.',
      videos: 434,
      concepts: 8,
    },
    {
      title: 'Apply models to multiplication and division problems, equivalent fractions, decimals, measurement conversions, interpreting data with line plots, angles & symmetry.',
      videos: 593,
      concepts: 12,
    },
    {
      title: 'Derive patterns, addition, subtracting, multiplying and dividing fractions, working with decimals, introduction to coordinate planes, volume.',
      videos: 417,
      concepts: 11,
    },
    {
      title: 'Understanding negative numbers, algebraic expressions, solving one-step equations, inequalities, ratios, unit rates and percentages, extend to working on nets and surface areas.',
      videos: 464,
      concepts: 14,
    },
    {
      title: 'Solve multi-step real life word problems with rational numbers (any form), linear expressions, ratio and proportion, scale factors, and diving into understanding probability models.',
      videos: 271,
      concepts: 5,
    },
    {
      title: 'Solving linear equations, simultaneous linear equations, working with slopes, rules on exponents, diving into functions, work on transformation and Pythagorean Theorem.',
      videos: 286,
      concepts: 5,
    },
  ],
};

export default videoMeta;
